Repository 1Password/for-open-source, pull requests merged in 2024-01, with the labels that each got.

#858 Adds Helsinki Ruby
  README.md
Labels: approved, dev-outreach

#859 Add Inspektor Gadget
  README.md
Labels: approved, dev-outreach

#860 Add dbt-athena
  README.md
Labels: approved

#861 Add nt_tool
  README.md
Labels: approved

#864 Add LineageOS
  README.md
Labels: approved, dev-outreach

#865 Add tiny11builder
  README.md
Labels: approved, dev-outreach

#867 Added Qdrant Operator
  README.md
Labels: approved

#868 Add Alveus Sanctuary
  README.md
Labels: approved, dev-outreach

#870 Add dujiaoka-docker
  README.md
Labels: approved

#871 Add Spatie
  README.md
Labels: approved, dev-outreach

#872 Add EvoEsports
  README.md
Labels: approved, dev-outreach

#876 Add vue-tel-input
  README.md
Labels: approved

#879 feat: add ishare
  README.md
Labels: approved, dev-outreach

#873 Add Steamauto
  README.md
Labels: approved, dev-outreach

#880 Add Python Brasil
  README.md
Labels: approved

#881 Add Leptos to Readme (#1)
  README.md
Labels: approved, dev-outreach

#882 Add hexo-theme-redefine
  README.md
Labels: approved, dev-outreach

#883 Adding PyOhio
  README.md
Labels: approved, dev-outreach

#884 Add Python India
  README.md
Labels: approved, dev-outreach

#878 docs: add DallasNews
  README.md
Labels: on-hold

#886 Add Kubeflow
  README.md
Labels: approved, dev-outreach

#887 Add pyiron
  README.md
Labels: approved, dev-outreach

#877 1Password
  README.md
Labels: approved, dev-outreach
